package model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Provides low-level database access functionality.
 * <p>
 * The {@code DB} class is responsible for establishing and managing a
 * direct connection to a MySQL database using JDBC. It offers basic
 * query execution capabilities and serves as a base class for
 * table-specific Data Access Objects (DAOs).
 * </p>
 *
 * <p>
 * This class handles:
 * <ul>
 *     <li>JDBC driver initialization</li>
 *     <li>Database connection management</li>
 *     <li>Execution of raw SQL queries and updates</li>
 *     <li>Lifecycle management of JDBC resources</li>
 * </ul>
 * </p>
 *
 * <p>
 * Higher-level DAO classes are expected to extend this class and
 * translate raw {@link ResultSet} data into domain objects.
 * </p>
 *
 * @author Mochammad Azka Basria
 */
public class DB {

    /**
     * JDBC connection string for the MySQL database.
     * <p>
     * Includes authentication credentials and connection parameters
     * required for local development.
     * </p>
     */
    private String conAddress =
            "jdbc:mysql://localhost:3306/db_hide_seek?user=root&password=&useSSL=false&allowPublicKeyRetrieval=true";

    /** JDBC statement used to execute SQL commands. */
    protected Statement stmt = null;

    /** Result set holding data returned from SELECT queries. */
    protected ResultSet rs = null;

    /** Active JDBC connection to the database. */
    protected Connection conn = null;

    /**
     * Constructs a new {@code DB} instance and immediately establishes
     * a database connection.
     * <p>
     * The constructor loads the MySQL JDBC driver and opens a connection
     * using the configured connection string. Transaction isolation is
     * set to allow non-blocking reads.
     * </p>
     *
     * @throws Exception   if the JDBC driver cannot be loaded
     * @throws SQLException if the database connection fails
     */
    public DB() throws Exception, SQLException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();

            conn = DriverManager.getConnection(conAddress);
            conn.setTransactionIsolation(Connection.TRANSACTION_READ_UNCOMMITTED);

        } catch (SQLException es) {
            throw es;
        }
    }

    /**
     * Executes a SQL SELECT query.
     * <p>
     * If the query produces a result set, it is stored internally and
     * can be retrieved using {@link #getResult()}.
     * </p>
     *
     * @param query the SQL SELECT statement to execute
     * @throws Exception   if a general execution error occurs
     * @throws SQLException if the SQL statement is invalid or fails
     */
    public void createQuery(String query) throws Exception, SQLException {
        try {
            stmt = conn.createStatement();

            if (stmt.execute(query)) {
                rs = stmt.getResultSet();
            }
        } catch (SQLException es) {
            throw es;
        }
    }

    /**
     * Executes a SQL data manipulation statement.
     * <p>
     * This method is intended for INSERT, UPDATE, or DELETE operations
     * and does not produce a {@link ResultSet}.
     * </p>
     *
     * @param query the SQL update statement to execute
     * @throws Exception   if a general execution error occurs
     * @throws SQLException if the SQL execution fails
     */
    public void createUpdate(String query) throws Exception, SQLException {
        try {
            stmt = conn.createStatement();
            stmt.executeUpdate(query);
        } catch (SQLException es) {
            throw es;
        }
    }

    /**
     * Returns the {@link ResultSet} generated by the last executed query.
     *
     * @return the current result set, or {@code null} if none exists
     * @throws Exception if result retrieval fails
     */
    public ResultSet getResult() throws Exception {
        try {
            return rs;
        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * Closes the active {@link ResultSet} and {@link Statement}.
     * <p>
     * This method should be invoked after query processing is complete
     * to release database resources.
     * </p>
     *
     * @throws Exception if an error occurs during resource cleanup
     */
    public void closeResult() throws Exception {
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException sqlEx) {
                rs = null;
                throw sqlEx;
            }
        }

        if (stmt != null) {
            try {
                stmt.close();
            } catch (SQLException sqlEx) {
                stmt = null;
                throw sqlEx;
            }
        }
    }

    /**
     * Closes the database connection.
     * <p>
     * This method terminates the physical JDBC connection and should be
     * called when the application no longer requires database access.
     * </p>
     *
     * @throws Exception if closing the connection fails
     */
    public void closeConnection() throws Exception {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException sqlEx) {
                conn = null;
            }
        }
    }
}
